Load the data in 'world_bank_turkey.csv' file.

Change the labels as follows (old label --> new label).

Urban population (% of total population) --> Urban Ratio

Population, total --> Total

Population, male -->Male

Population, female --> Female

Population growth (annual %) --> Population Growth

Life expectancy at birth, total (years) --> Life Expectancy

Armed forces personnel, total --> Armed Forces Personnel

Literacy rate, adult total (% of people ages 15 and above) --> Literacy Rate

In [2]:
import pandas as pd
world_bank_turkey = pd.read_csv('world_bank_turkey.csv')
world_bank_turkey.rename(columns = {"Urban population (% of total population)":"Urban Ratio" , "Population, total" : "Total" , "Population, male":"Male" , "Population, female" : "Female" , "Population growth (annual %)":"Population Growth" , "Life expectancy at birth, total (years)" : "Life Expectancy", "Armed forces personnel, total" : "Armed Forces Personnel", "Literacy rate, adult total (% of people ages 15 and above)" : "Literacy Rate"}, inplace = True)
world_bank_turkey

,Years,"Binding coverage, manufactured products (%)",Import volume index (2000 = 100),Merchandise trade (% of GDP),"International tourism, expenditures (% of total imports)","International tourism, expenditures (current US$)","International tourism, expenditures for travel items (current US$)","International tourism, receipts for travel items (current US$)","International tourism, expenditures for passenger transport items (current US$)","International tourism, receipts for passenger transport items (current US$)",...,"Net official flows from UN agencies, UNAIDS (current US$)","Net financial flows, RDB nonconcessional (NFL, current US$)","Net financial flows, RDB concessional (NFL, current US$)","PPG, private creditors (NFL, current US$)","PPG, other private creditors (NFL, current US$)","PNG, commercial banks and other creditors (NFL, current US$)","PNG, bonds (NFL, current US$)","Commercial banks and other lending (PPG + PNG) (NFL, current US$)","PPG, commercial banks (NFL, current US$)","PPG, bonds (NFL, current US$)"
0,1960,NaN,NaN,5.637700,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961,NaN,NaN,10.689847,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1962,NaN,NaN,11.207970,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1963,NaN,NaN,10.197425,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964,NaN,NaN,8.481113,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1965,NaN,NaN,8.657382,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1966,NaN,NaN,8.574468,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1967,NaN,NaN,7.715199,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1968,NaN,NaN,7.200000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1969,NaN,NaN,6.873288,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1970,NaN,NaN,8.989313,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-17089000.0,-1.281500e+07,-11413000.0,-2.200000e+06,0.000000e+00,-1.468500e+07,-1.072000e+06,-3.290000e+05
11,1971,NaN,NaN,11.367677,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,316946.4,4.698400e+07,21540000.0,6.600000e+06,0.000000e+00,5.394400e+07,2.580400e+07,-3.600000e+05
12,1972,NaN,NaN,11.981736,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-52041779.4,1.608700e+07,19844000.0,2.150000e+07,0.000000e+00,3.799000e+07,-3.354000e+06,-4.030000e+05
13,1973,NaN,NaN,13.228695,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.175700e+07,19516000.0,4.510000e+07,0.000000e+00,5.737000e+07,-7.246000e+06,-5.130000e+05
14,1974,NaN,NaN,14.915766,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,2.338300e+07,27487000.0,2.730000e+07,0.000000e+00,5.124200e+07,-3.545000e+06,-5.580000e+05
15,1975,NaN,NaN,13.756419,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,-2.638000e+07,-23374000.0,1.590000e+07,0.000000e+00,-9.804000e+06,-2.330000e+06,-6.760000e+05
16,1976,NaN,NaN,13.824067,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.571670e+08,32482000.0,1.048000e+08,0.000000e+00,2.388770e+08,1.015950e+08,2.309000e+07
17,1977,NaN,NaN,12.865388,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,4.182590e+08,41617000.0,2.184000e+08,0.000000e+00,6.374650e+08,3.774480e+08,-8.060000e+05
18,1978,NaN,NaN,10.571473,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,3.242590e+08,80907000.0,1.220000e+08,0.000000e+00,4.473920e+08,2.444850e+08,-1.134000e+06
19,1979,NaN,NaN,8.200766,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,2.994533e+09,81498000.0,7.300000e+07,0.000000e+00,3.068803e+09,2.914305e+09,-1.270000e+06
20,1980,NaN,13.192984,15.729193,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,5.957920e+08,151096000.0,4.600000e+07,0.000000e+00,6.430150e+08,4.459190e+08,-1.223000e+06
21,1981,NaN,10.643323,19.194814,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,-2.417800e+07,1074000.0,1.400000e+07,0.000000e+00,-4.910000e+06,-1.998400e+07,-5.268000e+06
22,1982,NaN,7.275473,22.602369,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.326170e+08,-183046000.0,1.300000e+07,0.000000e+00,1.508510e+08,3.208970e+08,-5.234000e+06
23,1983,NaN,6.094994,24.259756,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.337300e+08,76320000.0,5.000000e+06,0.000000e+00,1.427330e+08,6.141300e+07,-4.004000e+06
24,1984,NaN,4.885252,29.823349,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,2.507210e+08,20130000.0,2.600000e+07,0.000000e+00,2.825700e+08,2.364400e+08,-5.849000e+06
25,1985,NaN,14.866209,28.708284,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,9.259900e+07,13095000.0,-9.200000e+07,0.000000e+00,6.251000e+06,8.515600e+07,-5.652000e+06
26,1986,NaN,17.266723,24.511406,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.096258e+09,388107000.0,1.017190e+08,0.000000e+00,1.203379e+09,7.135530e+08,-5.403000e+06
27,1987,NaN,20.616095,27.930734,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.128951e+09,343478000.0,1.555770e+08,0.000000e+00,1.099866e+09,6.008110e+08,1.846620e+08
28,1988,NaN,21.041708,28.614414,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,2.970279e+09,160777000.0,2.300000e+07,0.000000e+00,1.383179e+09,1.199402e+09,1.610099e+09
29,1989,NaN,27.860425,25.589083,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.468205e+09,89458000.0,1.471850e+08,1.600000e+07,5.715990e+08,3.349560e+08,1.043792e+09
30,1990,NaN,37.199256,23.402487,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,8.036080e+08,-24990000.0,2.597030e+08,0.000000e+00,4.454890e+08,2.107760e+08,6.178220e+08
31,1991,NaN,36.090060,23.090382,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,5.767560e+08,815761000.0,-3.193660e+08,0.000000e+00,-2.437980e+08,-7.401930e+08,5.011870e+08
32,1992,NaN,40.349197,23.720312,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,2.100896e+09,-258802000.0,1.453480e+09,5.000000e+07,8.836320e+08,-3.110460e+08,2.670744e+09
33,1993,NaN,55.096214,24.849345,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,3.527218e+09,413144000.0,2.592902e+09,-1.600000e+07,2.512007e+09,-4.940390e+08,3.608113e+09
34,1994,NaN,41.052937,31.659611,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.065130e+08,279958000.0,-2.357960e+08,9.945000e+07,-4.942210e+08,-5.383830e+08,3.649390e+08
35,1995,47.25,53.703061,33.813424,2.271084,9.110000e+08,9.110000e+08,4.957000e+09,NaN,NaN,...,NaN,0.0,0.0,5.698600e+07,-246285000.0,7.438610e+08,0.000000e+00,1.688040e+08,-3.287720e+08,6.320440e+08
36,1996,46.95,69.604083,36.849591,2.594499,1.265000e+09,1.265000e+09,5.650000e+09,NaN,NaN,...,NaN,0.0,0.0,2.115040e+09,-84967000.0,9.990000e+08,2.500000e+07,1.553216e+09,6.391830e+08,1.560825e+09
37,1997,46.95,84.851386,39.413247,3.082782,1.716000e+09,1.716000e+09,7.002000e+09,NaN,NaN,...,NaN,0.0,0.0,2.628392e+09,102345000.0,1.177000e+09,-5.000000e+07,1.771640e+09,4.922950e+08,2.033752e+09
38,1998,46.95,83.420912,26.399661,3.210279,1.754000e+09,1.754000e+09,7.177000e+09,NaN,NaN,...,NaN,0.0,0.0,-6.191810e+08,-225708000.0,2.600000e+09,6.700000e+08,2.843444e+09,4.691520e+08,-8.626260e+08
39,1999,46.95,77.731672,26.110629,3.080564,1.471000e+09,1.471000e+09,5.203000e+09,NaN,NaN,...,NaN,0.0,0.0,4.395004e+09,-449203000.0,3.523346e+09,5.520200e+08,4.964809e+09,1.890666e+09,2.953541e+09
40,2000,46.95,100.000000,30.140737,2.806586,1.713000e+09,1.713000e+09,7.636000e+09,NaN,NaN,...,NaN,0.0,0.0,7.158848e+09,-515440000.0,9.505130e+08,4.541060e+08,2.987479e+09,2.552406e+09,5.121882e+09
41,2001,46.95,76.167357,36.320749,3.933017,1.738000e+09,1.738000e+09,1.006700e+10,NaN,NaN,...,NaN,0.0,0.0,-1.205515e+09,-366966000.0,-1.017000e+09,-1.244500e+08,-1.898712e+09,-5.147460e+08,-3.238030e+08
42,2002,46.14,96.063010,36.746084,3.530185,1.880000e+09,1.880000e+09,1.190100e+10,NaN,NaN,...,NaN,0.0,0.0,7.345720e+08,-209745000.0,6.934198e+09,2.000000e+08,7.008490e+09,2.840370e+08,6.602800e+08
43,2003,46.14,116.018346,37.390763,2.874087,2.113000e+09,2.113000e+09,1.320300e+10,NaN,NaN,...,NaN,0.0,0.0,1.416303e+09,-325678000.0,1.766252e+10,-4.309780e+08,1.593712e+10,-1.399718e+09,3.141699e+09
44,2004,46.14,140.716030,39.701646,2.483665,2.524000e+09,2.524000e+09,1.588800e+10,NaN,NaN,...,NaN,0.0,0.0,1.450723e+09,-294638000.0,1.072402e+10,5.277580e+08,1.041099e+10,-1.839500e+07,1.763756e+09
45,2005,46.14,157.462601,37.942524,2.887475,3.563000e+09,3.104000e+09,1.919100e+10,459000000.0,1.569000e+09,...,80000.0,0.0,0.0,4.497450e+08,-278517000.0,1.483643e+10,1.975000e+09,1.394174e+10,-6.161800e+08,1.344442e+09
46,2006,46.14,173.259452,40.745038,2.394765,3.517000e+09,2.989000e+09,1.745700e+10,528000000.0,1.680000e+09,...,80000.0,0.0,0.0,2.750409e+09,-197724000.0,2.898516e+10,1.726971e+09,2.858236e+10,-2.050690e+08,3.153203e+09
47,2007,47.26,192.501429,41.039844,2.388211,4.254000e+09,3.649000e+09,1.943000e+10,605000000.0,2.232000e+09,...,110000.0,0.0,0.0,5.320951e+09,73114000.0,3.335572e+10,7.500000e+08,3.390436e+10,4.755350e+08,4.772301e+09
48,2008,47.26,190.432078,43.696902,2.126646,4.509000e+09,3.824000e+09,2.336500e+10,685000000.0,3.081000e+09,...,60000.0,0.0,0.0,6.410940e+08,250484000.0,2.188697e+10,1.500000e+08,2.231765e+10,1.801980e+08,2.104120e+08
49,2009,47.26,165.163103,37.706478,3.338809,5.061000e+09,4.575000e+09,2.298000e+10,486000000.0,3.351000e+09,...,20000.0,0.0,0.0,2.957270e+08,130745000.0,-1.314160e+10,-2.000000e+08,-1.431042e+10,-1.299567e+09,1.464549e+09
50,2010,47.26,200.673953,38.790817,2.952477,5.817000e+09,5.194000e+09,2.258500e+10,623000000.0,3.733000e+09,...,130000.0,0.0,0.0,4.709233e+09,92283000.0,-7.317000e+09,1.880000e+09,-6.697506e+09,5.272110e+08,4.089739e+09
51,2011,47.26,226.718391,45.133731,2.127339,5.372000e+09,4.883000e+09,2.505400e+10,489000000.0,5.248000e+09,...,NaN,68985998.1,0.0,2.159235e+09,-11885000.0,8.091274e+09,1.562804e+09,8.715739e+09,6.363500e+08,1.534769e+09
52,2012,NaN,228.606498,44.509714,1.846252,4.585000e+09,4.094000e+09,2.534500e+10,491000000.0,6.221000e+09,...,NaN,25487275.0,0.0,5.410878e+09,-87139000.0,9.914000e+09,6.561000e+09,9.672051e+09,-1.548100e+08,5.652827e+09
53,2013,47.54,247.126334,42.444008,1.972698,5.253000e+09,4.817000e+09,2.799700e+10,436000000.0,8.195000e+09,...,NaN,4258353.3,0.0,5.452495e+09,-115045000.0,1.681300e+10,6.669511e+09,1.615223e+10,-5.457220e+08,6.113262e+09
54,2014,NaN,244.850342,42.795229,2.123830,5.475000e+09,5.072000e+09,2.955200e+10,403000000.0,9.303000e+09,...,NaN,7136121.3,0.0,4.802923e+09,-297666000.0,1.935700e+10,7.134127e+09,1.819530e+10,-8.640340e+08,5.964624e+09
55,2015,47.54,248.133862,40.832086,2.549459,5.683000e+09,5.368000e+09,2.661600e+10,315000000.0,8.981000e+09,...,NaN,4209421.5,0.0,1.636201e+09,-240687000.0,-7.732936e+09,5.167570e+08,-8.596436e+09,-6.228130e+08,2.499701e+09
56,2016,47.54,262.006669,39.497447,2.352583,5.025000e+09,4.783000e+09,1.874300e+10,242000000.0,8.045000e+09,...,NaN,17569912.3,0.0,5.140996e+09,-103023000.0,1.299458e+10,1.275354e+09,1.510397e+10,2.212411e+09,3.031608e+09
57,2017,NaN,286.899818,45.831317,2.079303,5.181000e+09,4.823000e+09,2.247800e+10,358000000.0,9.392000e+09,...,NaN,48666515.2,0.0,5.404901e+09,-158098000.0,9.591904e+09,3.289142e+09,8.768772e+09,-6.650340e+08,6.228033e+09
58,2018,NaN,259.609249,50.692012,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,44298935.4,0.0,4.215792e+09,-48258000.0,-2.991073e+09,-1.436269e+09,-2.009312e+09,1.030019e+09,3.234032e+09
59,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Show the first 15 rows of the table
world_bank_turkey.head(15)

,Years,"Binding coverage, manufactured products (%)",Import volume index (2000 = 100),Merchandise trade (% of GDP),"International tourism, expenditures (% of total imports)","International tourism, expenditures (current US$)","International tourism, expenditures for travel items (current US$)","International tourism, receipts for travel items (current US$)","International tourism, expenditures for passenger transport items (current US$)","International tourism, receipts for passenger transport items (current US$)",...,"Net official flows from UN agencies, UNAIDS (current US$)","Net financial flows, RDB nonconcessional (NFL, current US$)","Net financial flows, RDB concessional (NFL, current US$)","PPG, private creditors (NFL, current US$)","PPG, other private creditors (NFL, current US$)","PNG, commercial banks and other creditors (NFL, current US$)","PNG, bonds (NFL, current US$)","Commercial banks and other lending (PPG + PNG) (NFL, current US$)","PPG, commercial banks (NFL, current US$)","PPG, bonds (NFL, current US$)"
0,1960,NaN,NaN,5.637700,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961,NaN,NaN,10.689847,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1962,NaN,NaN,11.207970,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1963,NaN,NaN,10.197425,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964,NaN,NaN,8.481113,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1965,NaN,NaN,8.657382,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1966,NaN,NaN,8.574468,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1967,NaN,NaN,7.715199,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1968,NaN,NaN,7.200000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1969,NaN,NaN,6.873288,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1970,NaN,NaN,8.989313,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-17089000.0,-12815000.0,-11413000.0,-2200000.0,0.0,-14685000.0,-1072000.0,-329000.0
11,1971,NaN,NaN,11.367677,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,316946.4,46984000.0,21540000.0,6600000.0,0.0,53944000.0,25804000.0,-360000.0
12,1972,NaN,NaN,11.981736,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-52041779.4,16087000.0,19844000.0,21500000.0,0.0,37990000.0,-3354000.0,-403000.0
13,1973,NaN,NaN,13.228695,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,11757000.0,19516000.0,45100000.0,0.0,57370000.0,-7246000.0,-513000.0
14,1974,NaN,NaN,14.915766,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,23383000.0,27487000.0,27300000.0,0.0,51242000.0,-3545000.0,-558000.0

In [4]:
# Add a new column to the table which shows the Rural ratio of the population. Name the column as 'Rural Ratio'
rural_ratio = world_bank_turkey["Rural population"] / world_bank_turkey["Total"]
world_bank_turkey.insert(4, "Rural Ratio", rural_ratio*100) # i prefered to insert it as the fifth column
world_bank_turkey.head(5) # let's check

,Years,"Binding coverage, manufactured products (%)",Import volume index (2000 = 100),Merchandise trade (% of GDP),Rural Ratio,"International tourism, expenditures (% of total imports)","International tourism, expenditures (current US$)","International tourism, expenditures for travel items (current US$)","International tourism, receipts for travel items (current US$)","International tourism, expenditures for passenger transport items (current US$)",...,"Net official flows from UN agencies, UNAIDS (current US$)","Net financial flows, RDB nonconcessional (NFL, current US$)","Net financial flows, RDB concessional (NFL, current US$)","PPG, private creditors (NFL, current US$)","PPG, other private creditors (NFL, current US$)","PNG, commercial banks and other creditors (NFL, current US$)","PNG, bonds (NFL, current US$)","Commercial banks and other lending (PPG + PNG) (NFL, current US$)","PPG, commercial banks (NFL, current US$)","PPG, bonds (NFL, current US$)"
0,1960,NaN,NaN,5.637700,68.484998,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961,NaN,NaN,10.689847,67.936001,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1962,NaN,NaN,11.207970,67.402000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1963,NaN,NaN,10.197425,66.863001,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964,NaN,NaN,8.481113,66.320000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Select the following columns from the table and show its first 15 rows.
Years,Total,Urban Ratio,Rural Ratio,Male,Female,Population Growth,Life Expectancy,Armed Forces Personnel,Technicians in R&D (per million people),Researchers in R&D (per million people),Literacy Rate, Military expenditure (% of GDP)

In [5]:
world_bank_turkey2 = world_bank_turkey[["Years", "Total", "Urban Ratio", "Rural Ratio", "Male", "Female", "Population Growth", "Life Expectancy", "Armed Forces Personnel", "Technicians in R&D (per million people)", "Researchers in R&D (per million people)", "Literacy Rate", "Military expenditure (% of GDP)"]]
world_bank_turkey2.head(15)

,Years,Total,Urban Ratio,Rural Ratio,Male,Female,Population Growth,Life Expectancy,Armed Forces Personnel,Technicians in R&D (per million people),Researchers in R&D (per million people),Literacy Rate,Military expenditure (% of GDP)
0,1960,27472345.0,31.515,68.484998,13692632.0,13779713.0,2.445590,45.369,NaN,NaN,NaN,NaN,3.531571
1,1961,28146910.0,32.064,67.936001,14021104.0,14125806.0,2.425772,46.093,NaN,NaN,NaN,NaN,3.764543
2,1962,28832827.0,32.598,67.402000,14355672.0,14477155.0,2.407698,46.830,NaN,NaN,NaN,NaN,3.711083
3,1963,29531365.0,33.137,66.863001,14696916.0,14834449.0,2.393835,47.573,NaN,NaN,NaN,NaN,3.387339
4,1964,30244261.0,33.680,66.320000,15045655.0,15198606.0,2.385353,48.312,NaN,NaN,NaN,NaN,3.422465
5,1965,30972994.0,34.227,65.772999,15402595.0,15570399.0,2.380922,49.035,NaN,NaN,NaN,NaN,3.554419
6,1966,31717507.0,34.949,65.050998,15767534.0,15949973.0,2.375314,49.733,NaN,NaN,NaN,NaN,3.143981
7,1967,32477992.0,35.759,64.241000,16140610.0,16337382.0,2.369389,50.406,NaN,NaN,NaN,NaN,3.259574
8,1968,33256464.0,36.577,63.423000,16523261.0,16733203.0,2.368646,51.053,NaN,NaN,NaN,NaN,3.275556
9,1969,34055390.0,37.401,62.599001,16917300.0,17138090.0,2.373916,51.678,NaN,NaN,NaN,NaN,3.079338
10,1970,34876303.0,38.234,61.765999,17323819.0,17552484.0,2.381928,52.286,NaN,NaN,NaN,NaN,3.256489
11,1971,35720599.0,38.945,61.055001,17743665.0,17976934.0,2.391992,52.887,NaN,NaN,NaN,NaN,3.499794
12,1972,36587261.0,39.600,60.400001,18175924.0,18411337.0,2.397259,53.492,NaN,NaN,NaN,NaN,3.445521
13,1973,37472336.0,40.258,59.742000,18617713.0,18854623.0,2.390283,54.109,NaN,NaN,NaN,NaN,3.349451
14,1974,38370283.0,40.920,59.079999,19065031.0,19305252.0,2.368033,54.741,NaN,NaN,NaN,NaN,3.193021

Show the year with the all other selected columns in which personnel in the Armed forces is maximum among all years.

In [7]:
armed_personnel_max = world_bank_turkey2[ world_bank_turkey2["Armed Forces Personnel"].notna()].max()
armed_personnel_max["Years"]

2017.0

Show the years where more people live in urban areas than rural areas

In [8]:
urban_greater_than_rural = world_bank_turkey2[world_bank_turkey2["Urban Ratio"] > world_bank_turkey2["Rural Ratio"]]
urban_greater_than_rural[urban_greater_than_rural["Urban Ratio"].notna()] # i want to retrieve the non-null values
# urban_greater_than_rural["Years"].array # such years can be seen as pandasarray
urban_greater_than_rural[["Years"]] # such years can be seen as a dataframe

    Years
24   1984
25   1985
26   1986
27   1987
28   1988
29   1989
30   1990
31   1991
32   1992
33   1993
34   1994
35   1995
36   1996
37   1997
38   1998
39   1999
40   2000
41   2001
42   2002
43   2003
44   2004
45   2005
46   2006
47   2007
48   2008
49   2009
50   2010
51   2011
52   2012
53   2013
54   2014
55   2015
56   2016
57   2017
58   2018

Show the years where Techinicians in R&D is not nan

In [9]:
technicians_in_rd_notna = world_bank_turkey2[world_bank_turkey2["Technicians in R&D (per million people)"].notna()]
technicians_in_rd_notna[["Years"]]
# such years can be observed as a dataframe. i have opted to display only the year column as it is stated "show the years..."

    Years
36   1996
37   1997
38   1998
39   1999
40   2000
41   2001
42   2002
43   2003
44   2004
45   2005
46   2006
47   2007
48   2008
49   2009
50   2010
51   2011
52   2012
53   2013
54   2014
55   2015
56   2016
57   2017

Show the minimum  literacy rate which is not nan

In [10]:
min_literacy_values = world_bank_turkey2[ world_bank_turkey2["Literacy Rate"].notna()].min()
min_literacy_values["Literacy Rate"]

61.62768173

Add a new column which shows the Armed Personel Ratio with respect to the total population

In [11]:
# write your answer here
armed_personnel_ratio = world_bank_turkey2["Armed Forces Personnel"] / world_bank_turkey2["Total"]
world_bank_turkey2.insert(9, "Armed Personel Ratio", armed_personnel_ratio)
world_bank_turkey2

,Years,Total,Urban Ratio,Rural Ratio,Male,Female,Population Growth,Life Expectancy,Armed Forces Personnel,Armed Personel Ratio,Technicians in R&D (per million people),Researchers in R&D (per million people),Literacy Rate,Military expenditure (% of GDP)
0,1960,27472345.0,31.515,68.484998,13692632.0,13779713.0,2.445590,45.369,NaN,NaN,NaN,NaN,NaN,3.531571
1,1961,28146910.0,32.064,67.936001,14021104.0,14125806.0,2.425772,46.093,NaN,NaN,NaN,NaN,NaN,3.764543
2,1962,28832827.0,32.598,67.402000,14355672.0,14477155.0,2.407698,46.830,NaN,NaN,NaN,NaN,NaN,3.711083
3,1963,29531365.0,33.137,66.863001,14696916.0,14834449.0,2.393835,47.573,NaN,NaN,NaN,NaN,NaN,3.387339
4,1964,30244261.0,33.680,66.320000,15045655.0,15198606.0,2.385353,48.312,NaN,NaN,NaN,NaN,NaN,3.422465
5,1965,30972994.0,34.227,65.772999,15402595.0,15570399.0,2.380922,49.035,NaN,NaN,NaN,NaN,NaN,3.554419
6,1966,31717507.0,34.949,65.050998,15767534.0,15949973.0,2.375314,49.733,NaN,NaN,NaN,NaN,NaN,3.143981
7,1967,32477992.0,35.759,64.241000,16140610.0,16337382.0,2.369389,50.406,NaN,NaN,NaN,NaN,NaN,3.259574
8,1968,33256464.0,36.577,63.423000,16523261.0,16733203.0,2.368646,51.053,NaN,NaN,NaN,NaN,NaN,3.275556
9,1969,34055390.0,37.401,62.599001,16917300.0,17138090.0,2.373916,51.678,NaN,NaN,NaN,NaN,NaN,3.079338
10,1970,34876303.0,38.234,61.765999,17323819.0,17552484.0,2.381928,52.286,NaN,NaN,NaN,NaN,NaN,3.256489
11,1971,35720599.0,38.945,61.055001,17743665.0,17976934.0,2.391992,52.887,NaN,NaN,NaN,NaN,NaN,3.499794
12,1972,36587261.0,39.600,60.400001,18175924.0,18411337.0,2.397259,53.492,NaN,NaN,NaN,NaN,NaN,3.445521
13,1973,37472336.0,40.258,59.742000,18617713.0,18854623.0,2.390283,54.109,NaN,NaN,NaN,NaN,NaN,3.349451
14,1974,38370283.0,40.920,59.079999,19065031.0,19305252.0,2.368033,54.741,NaN,NaN,NaN,NaN,NaN,3.193021
15,1975,39277258.0,41.586,58.413999,19515020.0,19762238.0,2.336239,55.387,NaN,NaN,NaN,NaN,61.627682,5.119454
16,1976,40189567.0,42.087,57.913000,19965707.0,20223860.0,2.296176,56.046,NaN,NaN,NaN,NaN,NaN,4.943027
17,1977,41108297.0,42.508,57.492000,20417758.0,20690539.0,2.260254,56.709,NaN,NaN,NaN,NaN,NaN,4.713623
18,1978,42039992.0,42.931,57.069000,20874096.0,21165896.0,2.241138,57.370,NaN,NaN,NaN,NaN,NaN,4.187306
19,1979,42994041.0,43.355,56.645001,21339067.0,21654974.0,2.244017,58.023,NaN,NaN,NaN,NaN,NaN,3.357259
20,1980,43975971.0,43.780,56.220000,21815316.0,22160655.0,2.258185,58.667,NaN,NaN,NaN,NaN,65.694344,3.900313
21,1981,44988414.0,45.189,54.811001,22303791.0,22684623.0,2.276162,59.297,NaN,NaN,NaN,NaN,NaN,3.824532
22,1982,46025411.0,46.997,53.003001,22801877.0,23223534.0,2.278867,59.915,NaN,NaN,NaN,NaN,NaN,4.298151
23,1983,47073472.0,48.812,51.188000,23304392.0,23769080.0,2.251596,60.520,NaN,NaN,NaN,NaN,NaN,3.937605
24,1984,48114155.0,50.634,49.366001,23804245.0,24309910.0,2.186680,61.111,NaN,NaN,NaN,NaN,NaN,3.597094
25,1985,49133937.0,52.448,47.552001,24296183.0,24837754.0,2.097356,61.682,630000.0,0.012822,NaN,NaN,75.968239,3.531043
26,1986,50128541.0,53.930,46.070000,24778751.0,25349790.0,2.004055,62.231,NaN,NaN,NaN,NaN,NaN,3.637992
27,1987,51100924.0,55.261,44.738999,25252941.0,25847983.0,1.921205,62.758,NaN,NaN,NaN,NaN,NaN,3.328585
28,1988,52053765.0,56.587,43.413000,25718937.0,26334828.0,1.847455,63.266,NaN,NaN,NaN,NaN,NaN,2.932209
29,1989,52992487.0,57.899,42.101000,26177682.0,26814805.0,1.787302,63.763,780000.0,0.014719,NaN,NaN,NaN,3.148727
30,1990,53921760.0,59.203,40.796999,26630265.0,27291495.0,1.738396,64.256,769000.0,0.014261,NaN,NaN,79.232452,3.527706
31,1991,54840590.0,59.976,40.024000,27075877.0,27764713.0,1.689651,64.757,804000.0,0.014661,NaN,NaN,NaN,3.754364
32,1992,55748948.0,60.518,39.482001,27514969.0,28233979.0,1.642793,65.275,704000.0,0.012628,NaN,NaN,NaN,3.870567
33,1993,56653804.0,61.055,38.945000,27951499.0,28702305.0,1.610059,65.815,686000.0,0.012109,NaN,NaN,NaN,3.921417
34,1994,57564204.0,61.590,38.410000,28390751.0,29173453.0,1.594178,66.377,811000.0,0.014089,NaN,NaN,NaN,4.051359
35,1995,58486456.0,62.123,37.877000,28836439.0,29650017.0,1.589429,66.963,690000.0,0.011798,NaN,NaN,NaN,3.901650
36,1996,59423282.0,62.653,37.347000,29289965.0,30133317.0,1.589090,67.570,707200.0,0.011901,34.22905,304.34237,NaN,4.139697
37,1997,60372568.0,63.179,36.821000,29750113.0,30622455.0,1.584873,68.189,821200.0,0.013602,39.30598,313.18896,NaN,4.103672
38,1998,61329676.0,63.703,36.296999,30214694.0,31114982.0,1.572901,68.807,821200.0,0.013390,35.15432,308.57862,NaN,3.184501
39,1999,62287397.0,64.223,35.777000,30680242.0,31607155.0,1.549527,69.417,841200.0,0.013505,38.06553,322.13616,NaN,3.889017
40,2000,63240194.0,64.741,35.259000,31144047.0,32096147.0,1.518097,70.005,827700.0,0.013088,37.33389,365.00563,NaN,3.661095
41,2001,64192243.0,65.340,34.659999,31608455.0,32583788.0,1.494230,70.560,665100.0,0.010361,39.88069,353.66067,NaN,3.603457
42,2002,65145367.0,65.974,34.026001,32074318.0,33071049.0,1.473881,71.078,664800.0,0.010205,39.40558,368.34319,NaN,3.795927
43,2003,66089402.0,66.602,33.397999,32535902.0,33553500.0,1.438721,71.559,664800.0,0.010059,46.78766,494.20599,NaN,3.296047
44,2004,67010930.0,67.225,32.775000,32985599.0,34025331.0,1.384734,72.004,616000.0,0.009193,49.86442,505.56088,87.365490,2.697984
45,2005,67903469.0,67.840,32.160001,33419608.0,34483861.0,1.323138,72.424,617000.0,0.009086,69.99437,576.39203,88.229060,2.409371
46,2006,68756810.0,68.450,31.550001,33832700.0,34924110.0,1.248866,72.830,612000.0,0.008901,83.24908,620.43873,88.119390,2.418669
47,2007,69581848.0,69.053,30.947001,34230796.0,35351052.0,1.192794,73.235,612000.0,0.008795,106.61141,713.64656,88.655900,2.266971
48,2008,70418604.0,69.651,30.349000,34634721.0,35783883.0,1.195376,73.649,613000.0,0.008705,108.06074,749.72790,NaN,2.240845
49,2009,71321399.0,70.241,29.759000,35072771.0,36248628.0,1.273892,74.074,612800.0,0.008592,122.98332,809.63305,90.816720,2.536591
50,2010,72326988.0,70.825,29.175000,35564244.0,36762744.0,1.400093,74.507,612800.0,0.008473,143.12503,889.58536,92.660600,2.324126
51,2011,73443863.0,71.402,28.598000,36113020.0,37330843.0,1.532401,74.944,612800.0,0.008344,172.33009,982.27944,94.106090,2.078543
52,2012,74653016.0,71.974,28.026000,36709561.0,37943455.0,1.632958,75.373,612800.0,0.008209,190.22882,1101.28180,94.919750,2.054760
53,2013,75928564.0,72.531,27.469000,37342505.0,38586059.0,1.694203,75.784,612800.0,0.008071,198.33254,1175.32650,95.256660,1.963253
54,2014,77231907.0,73.077,26.923000,37994585.0,39237322.0,1.701972,76.172,612800.0,0.007935,208.79699,1163.91706,95.439630,1.902458
55,2015,78529409.0,73.611,26.389000,38650060.0,39879349.0,1.666052,76.532,512000.0,0.006520,221.25460,1215.77837,95.601420,1.847056
56,2016,79821724.0,74.134,25.866000,39310492.0,40511232.0,1.632251,76.860,512000.0,0.006414,317.45981,1259.65217,96.167330,2.067543
57,2017,81101892.0,74.644,25.356000,39971036.0,41130856.0,1.591059,77.161,512000.0,0.006313,355.36557,1385.75729,96.150530,2.068141
58,2018,82319724.0,75.143,24.857000,40601888.0,41717836.0,1.490445,NaN,NaN,NaN,NaN,NaN,NaN,2.504357
59,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN